name: predixs
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  equatable: ^2.0.7
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_riverpod: ^3.0.3
  gap: ^3.0.1
  go_router: ^17.0.0
  google_fonts: ^6.3.3
  image_picker: ^1.2.1
  intl: ^0.20.2
  pinput: ^6.0.1
  shared_preferences: ^2.5.4
  smooth_page_indicator: ^2.0.1
  supabase_flutter: ^2.10.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
